### PR TITLE
Fix nativeAddGas api doesn't detect gas unpaid correctly

### LINKED ISSUE #194: addNativeGas api doesn't detect gas unpaid correctly
There's a [report on discord](https://discord.com/channels/770814806105128977/955655587260170272/1036525287351001088) about adding gas for [a gmp call](https://testnet.axelarscan.io/gmp/0xd4d3f300b8b85295c42b3a2db98bae6a04958a4c5d2f026558eb76978d3f7165:14). it seems that the user hasn't paid gas for this call yet. (the [api](https://testnet.api.gmp.axelarscan.io/?method=searchGMP&txHash=0xd4d3f300b8b85295c42b3a2db98bae6a04958a4c5d2f026558eb76978d3f7165%3A14) shows "gas_status": "gas_unpaid"), but the sdk doesn't allow them to pay; instead, it returns Already paid sufficient gas fee . can you please have a look?

### PR DESCRIPTION
**Pull request by npty**
Fix #194 

Tests have now covered the issue:

image

### CODE REVIEW

File: src/libs/AxelarQueryAPI.ts [hunk 1]
```diff
@@ -53,16 +53,12 @@ export class AxelarQueryAPI {
...
-      return await this.axelarQueryClient.nexus.FeeInfo({ chain: chainName, asset: assetDenom });
-    } catch (e: any) {
-      throw e;
-    }
+    if (!this.axelarQueryClient)
+      this.axelarQueryClient = await AxelarQueryClient.initOrGetAxelarQueryClient({
+        environment: this.environment,
+        axelarRpcUrl: this.axelarRpcUrl,
+      });
+    return await this.axelarQueryClient.nexus.FeeInfo({ chain: chainName, asset: assetDenom });
```
Comment (vladwulf) [inline src/libs/AxelarQueryAPI.ts:61]: I think we can remove `await`

File: src/libs/AxelarQueryAPI.ts [hunk 2]
```diff
@@ -80,20 +76,16 @@ export class AxelarQueryAPI {
...
-        amount: `${amountInDenom.toString()}${assetDenom}`,
+    if (!this.axelarQueryClient)
+      this.axelarQueryClient = await AxelarQueryClient.initOrGetAxelarQueryClient({
+        environment: this.environment,
+        axelarRpcUrl: this.axelarRpcUrl,
       });
-    } catch (e: any) {
-      throw e;
-    }
+    return await this.axelarQueryClient.nexus.TransferFee({
```
Comment (vladwulf) [inline src/libs/AxelarQueryAPI.ts:84]: same

**Review by vladwulf — APPROVED** [review]

File: src/libs/AxelarQueryAPI.ts (hunk 2 above)
Comment (npty) [reply src/libs/AxelarQueryAPI.ts]: replace all 17 occurrences of `return await` https://github.com/axelarnetwork/axelarjs-sdk/pull/193/commits/8ec59dd55e97caf6259052f82a914601c140d013
