### PR TITLE
Fix cannot find chain `ethereum-2`

### LINKED ISSUE #200: The sdk returns "cannot find chainethereum-2" for `manualRelayToDestChain`
https://testnet.axelarscan.io/gmp/0x5408060a6e15e4f5fa04ea3bec0da8a01ce5585c48321c151264184f489bbd9e:32
the Approve button calls  `manualRelayToDestChain(transactionHash)` under the hood.

inage1

### PR DESCRIPTION
**Pull request by npty**
Close #200

### CODE REVIEW

File: src/libs/types/index.ts [hunk 1]
```diff
@@ -221,13 +221,13 @@ export interface ApproveGatewayResponse {
...
-    'moonbeam': GasToken.GLMR,
-    'aurora': GasToken.AURORA,
-    'biance': GasToken.BINANCE,
+    ethereum: GasToken.ETH,
+    avalanche: GasToken.AVAX,
+    fantom: GasToken.FTM,
+    polygon: GasToken.MATIC,
+    moonbeam: GasToken.GLMR,
+    aurora: GasToken.AURORA,
+    binance: GasToken.BINANCE,
```
Comment (npty) [inline src/libs/types/index.ts:230]: @vladwulf can you check if this change causes any effect on front-end?

**Review by vladwulf — APPROVED** [review]
